name: "Daily check and update"

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  check_and_update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install requirements
        run: |
          pip install git+https://github.com/thesadru/genshin.py
          pip install -r requirements.txt
      - name: Run main.py
        env:
          COOKIES: ${{ secrets.COOKIES }}
        run: |
          python main.py -t template_for_readme.html-o README.md
      - name: get html
        env:
          COOKIES: ${{ secrets.COOKIES }}
        run: |
          python main.py -o index.html
      - name: Format with prettier
        run: |
          npx prettier README.md --write --parser html
      - name: Commit and push if changed
        run: |
          git config user.name "Paimon"
          git config user.email "actions@users.noreply.github.com"
          git diff
          git add README.md codes.txt index.html
          git commit -m "mipohbopohih genshin stats." --allow-empty
          git push
